name: Build & Push Docker Image

on:
  push:
    branches: [main, master]
    tags:
      - 'v*'

env:
  REGISTRY: registry.zenservice.my.id
  IMAGE_NAME: elog_service

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.23'

    - name: Read .env
      run: |
        echo "Loading .env"
        set -o allexport
        source .env
        set +o allexport

    - name: Build Go binary
      run: |
        mkdir -p bin
        go build -ldflags "-s -w" -o bin/${{ env.IMAGE_NAME }} ./cmd/api

    - name: Set image version
      id: vars
      run: |
        TAG=$(git describe --tags --abbrev=0 || echo "0.0.0")
        COMMIT=$(git rev-parse --short HEAD)
        echo "tag=$TAG" >> $GITHUB_OUTPUT
        echo "commit=$COMMIT" >> $GITHUB_OUTPUT

    - name: Log in to Docker registry
      run: echo "${{ secrets.REGISTRY_PASSWORD }}" | docker login ${{ env.REGISTRY }} -u "${{ secrets.REGISTRY_USERNAME }}" --password-stdin

    - name: Build Docker image
      run: |
        docker build \
          --build-arg VERSION=${{ steps.vars.outputs.tag }} \
          --build-arg COMMIT=${{ steps.vars.outputs.commit }} \
          -t ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ steps.vars.outputs.tag }} \
          -t ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest .

    - name: Push Docker image
      run: |
        docker push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ steps.vars.outputs.tag }}
        docker push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest